project:
  output-dir: ../docs/slides

format:
  revealjs: 
    theme: [default, custom.scss]
    slide-number: true
    html-math-method: katex
    chalkboard: 
      buttons: false

    revealjs-plugins:
      - pointer

title-slide-attributes:
    data-background-image: "img/tuc-new-large.png"
    data-background-size: 30%
    data-background-opacity: "1"
    data-background-position: top

filters:
  - center_images.lua
  - quarto