# List of exercises

You will find below links to download the notebooks for the exercises (which you have to fill) and their solution (which you can look at after you finished the exercise). It is recommended not to look at the solution while doing the exercise unless you are lost. 

Alternatively, you can run the notebooks directly on Colab (<https://colab.research.google.com/>) if you have a Google account. 

For instructions on how to install a Python distribution on your computer, check this [page](Installation.qmd).

You will also find videos presenting the exercises and commenting their solution.

The solution of each exercise is rendered in the following pages.


## Introduction to Python

This exercise is an introduction to Python for absolute beginners. If you already know Python, you can safely skip it. 

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/1-Python.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/1-Python.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/1-Python-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/1-Python-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube lqJ-2Wrc5SI >}}

**Commented solution**

{{< youtube pBTwkxOSlpU >}}

## Numpy and Matplotlib

The goal of this exercise is to present the basics of the numerical library `numpy` as well as the visualization library `matplotlib`.


**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/2-Numpy.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/2-Numpy.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/2-Numpy-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/2-Numpy-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube 0FBuLT04r-M >}}


**Commented solution**

{{< youtube kngLlgI3eKU >}}

## Sampling

The goal of this exercise is to understand how to sample rewards from a n-armed bandits and to understand the central limit theorem.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/3-Sampling.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/3-Sampling.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/3-Sampling-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/3-Sampling-solution.ipynb){target="_blank"}.


**Presentation**

{{< youtube PEsCxwjlTyU >}}

**Commented solution**

{{< youtube E3fB4nyhoZ8 >}}

## Bandits - part 1

The goal of this exercise is to implement simple action selection mechanisms for the n-armed bandit:

* Greedy action selection
* $\epsilon$-greedy action selection
* Softmax action selection

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/4-Bandits.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/4-Bandits.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/4-Bandits-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/4-Bandits-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube pYxphhdmrD4 >}}

**Commented solution**

{{< youtube x60ffQE59Eo >}}

## Bandits - part 2 

The goal of this exercise is to further investigate the properties of the action selection algorithms for the n-armed bandit.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/5-Bandits2.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/5-Bandits2.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/5-Bandits2-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/5-Bandits2-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube xKiNrBm5lvk >}}

**Commented solution**

{{< youtube 24cJ-y0Ye-U >}}


## Dynamic programming

The goal of this exercise is to apply policy iteration and value iteration on the recycling robot MDP.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/6-DP.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/6-DP.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/6-DP-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/6-DP-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube hEb36jiXk-Q >}}

**Commented solution**

{{< youtube x0vUQNgwZJI >}}

## Gym

The goal of this exercise is to install `gym` and learn how to use its interface.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/7-Gym.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/7-Gym.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/7-Gym-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/7-Gym-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube uh-gqcIs6Gg >}}

**Commented solution**

{{< youtube MqTpeXPQ9jQ >}}

## Monte Carlo control

The goal of this exercise is to implement on-policy Monte-Carlo control on the Taxi gym environment.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/8-MonteCarlo.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/8-MonteCarlo.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/8-MonteCarlo-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/8-MonteCarlo-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube txT9_VYFYjA >}}

**Commented solution**

{{< youtube jNtnaBiOZnM >}}

## Temporal difference

The goal of this exercise is to implement Q-learning on the Taxi gym environment.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/9-TD.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/9-TD.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/9-TD-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/9-TD-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube WfnS22z2JKY >}}

**Commented solution**

{{< youtube uxcdOwlfQHA >}}

## Eligibility traces

The goal of this exercise is to implement Q-learning with eligibility traces on the Gridworld environment.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/10-Eligibilitytraces.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/10-Eligibilitytraces.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/10-Eligibilitytraces-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/10-Eligibilitytraces-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube OeUbBGp7Kes >}}

**Commented solution**

{{< youtube SUMCA8TsSX0 >}}

## Keras

The goal of this exercise is to quickly discover keras and to understand why neural networks (and SGD) need i.i.d. samples.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/11-Keras.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/11-Keras.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/11-Keras-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/11-Keras-solution.ipynb){target="_blank"}.


**Presentation**

{{< youtube kzW9DpigQCo >}}

**Commented solution**

{{< youtube hbAPFC7NEqc >}}

## DQN

The goal of this exercise is to implement DQN on the Cartpole balancing problem.

**Notebook:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/12-DQN.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/12-DQN.ipynb){target="_blank"}.

**Solution:** [download .ipynb](https://raw.githubusercontent.com/vitay/course-deeprl/master/notes/exercises/12-DQN-solution.ipynb){target="_blank"} or [run on colab](https://colab.research.google.com/github/vitay/course-deeprl/blob/master/notes/exercises/12-DQN-solution.ipynb){target="_blank"}.

**Presentation**

{{< youtube SHKuLVVq1SY >}}

**Commented solution**

{{< youtube cGsWOEyzYsU >}}