project:
  type: book
  output-dir: ../docs

book:
  title: "Deep Reinforcement Learning"
  author: "Julien Vitay"
  search: true
  sidebar:
    style: floating
    type: light
    logo: notes/img/tuc-new.png
  page-footer: "Copyright 2022, Julien Vitay - <julien.vitay@informatik.tu-chemnitz.de>" 
  execute: 
    enabled: false
  chapters:
    - index.qmd
    - part: "**Introduction**"
      chapters:
      - notes/1.1-Introduction.qmd
      - notes/1.2-Math.qmd
    - part: "**Tabular RL**"
      chapters:
      - notes/2.1-Bandits.qmd
      - notes/2.2-MDP.qmd
      - notes/2.3-DP.qmd
      - notes/2.4-MC.qmd
      - notes/2.5-TD.qmd
      - notes/2.6-FA.qmd
      - notes/2.7-NN.qmd
    - part: "**Model-free RL**"
      chapters:
      - notes/3.1-DQN.qmd
      - notes/3.2-BeyondDQN.qmd
      - notes/3.3-PG.qmd
      - notes/3.4-A3C.qmd
      - notes/3.5-DDPG.qmd
      - notes/3.6-PPO.qmd
      - notes/3.7-SAC.qmd
    - part: "**Model-based RL**"
      chapters:
      - notes/4.1-MB.qmd
      - notes/4.2-LearnedModels.qmd
      - notes/4.3-AlphaGo.qmd
      - notes/4.4-SR.qmd
    - part: "**Outlook**"
      chapters:
      - notes/5.1-Outlook.qmd
    - part: "**Exercises**"
      chapters:
      - exercises/Content.qmd
      - exercises/Installation.qmd
      - exercises/1-Python-solution.ipynb
      - exercises/2-Numpy-solution.ipynb
      - exercises/3-Sampling-solution.ipynb
      - exercises/4-Bandits-solution.ipynb
      - exercises/5-Bandits2-solution.ipynb
      - exercises/6-DP-solution.ipynb
      - exercises/7-Gym-solution.ipynb
      - exercises/8-MonteCarlo-solution.ipynb
      - exercises/9-TD-solution.ipynb
      - exercises/10-Eligibilitytraces-solution.ipynb
      - exercises/11-Keras-solution.ipynb
      - exercises/12-DQN-solution.ipynb
    - references.qmd


bibliography: 
  - DeepLearning.bib
  - ReinforcementLearning.bib
csl: frontiers.csl

format:
  html:
    theme: [journal, custom.scss]
    page-layout: full
    number-depth: 2
    number-sections: false
    toc: true
    smooth-scroll: true
    html-math-method: katex
    fig-cap-location: margin
    reference-location: margin

filters:
  - center_images.lua
  - quarto

